export const q41_70 = [
    {
        "type": "MÚLTIPLA ESCOLHA",
        "text": "Paciente de 52 anos queixa-se de diminuição da audição à direita. Ao exame com diapasão: no teste de Weber, o som lateraliza para a orelha direita; no teste de Rinne realizado à direita, a condução óssea é percebida por mais tempo que a condução aérea. Analise as assertivas:\nI. O teste de Rinne à direita está negativo.\nII. O conjunto dos achados é compatível com perda auditiva de condução na orelha direita.\nIII. Se a perda fosse neurossensorial à direita, o Weber lateralizaria para a orelha esquerda.\nIV. Rinne e Weber são testes concorrentes, devendo o examinador optar por apenas um deles.\nEstá correto o que se afirma em:",
        "interactionType": "multiple-choice",
        "options": [
            "A) Apenas I e IV estão corretas.",
            "B) Apenas I, II e III estão corretas.",
            "C) Apenas II e IV estão corretas.",
            "D) Apenas III e IV estão corretas.",
            "E) Todas as alternativas estão corretas."
        ],
        "gabarito": "Alternativa B (Apenas I, II e III estão corretas).\n\n**COMENTÁRIO DO GABARITO:**\n\n• I — VERDADEIRO: No teste de Weber, a vibração do diapasão posicionado na linha média do crânio (vértex ou fronte) atinge ambas as cócleas por via óssea com igual intensidade. Em indivíduos com audição normal ou com perda neurossensorial estritamente simétrica, o som é percebido igualmente em ambos os ouvidos (Weber indiferente / centralizado).\n• II — VERDADEIRO: Na perda auditiva condutiva do ouvido direito (ex.: cerúmen impactado, otite média com efusão, otoesclerose), há abolição do efeito mascarador do ruído ambiente e hiperdensidade de condução óssea local, fazendo com que o som do diapasão lateralize para o lado comprometido (Weber lateralizado para a direita).\n• III — VERDADEIRO: O teste de Rinne compara a condução aérea (CA) com a condução óssea (CO) no mesmo ouvido. Quando a condução óssea é ouvida por mais tempo ou mais intensamente que a condução aérea (CO > CA), o teste é denominado \"Rinne Negativo\", confirmando a existência de perda auditiva de condução naquele lado.\n• IV — FALSO: Os testes de Rinne e Weber NÃO são excludentes, mas sim estritamente COMPLEMENTARES na propedêutica otorrinolaringológica. Para se determinar com segurança se uma perda auditiva é condutiva ou neurossensorial (e diferenciar o falso Rinne negativo na cofose unilateral), é indispensável interpretar o resultado conjunto do Weber com o Rinne bilateral.\n• Resumo Semiológico: Apenas I, II e III estão corretas (Alternativa B)."
    },
    {
        "type": "MÚLTIPLA ESCOLHA",
        "text": "Homem, 30 anos, natural e procedente de Casa Nova (BA), agricultor, analfabeto, comparece ao consultório do Dr. Estaciano em Juazeiro, com queixa de que apresenta um \"caroço no pescoço\". Considerando esta situação, sinalize a(s) opção(ões) pertinentes:\nI. \"O tempo de apresentação, a localização precisa, progressão, a existência do achado em outros locais e o questionamento sobre febre, perda ponderal, sudorese noturna e astenia são quesitos indispensáveis para a decisão médica.\"\nII. \"O achado foi percebido há 5 dias e apresentou febre baixa por um dia, além de tosse seca e odinofagia, que ainda persistem. Não ocorreu perda ponderal e nega sudorese noturna. Sinais vitais normais. Observo um linfonodo submandibular direito de cerca de 0,5 cm, móvel, doloroso, de consistência amolecida. Noto vermelhidão em mucosa faríngea. Assim, farei encaminhamento para internamento hospitalar, sendo mandatória a biópsia do linfonodo.\"\nIII. \"O linfonodo supraclavicular associado a sintomas constitucionais sinaliza condições pouco mórbidas, não havendo necessidade de investigações pormenorizadas.\"\nIV. \"Não posso abrir mão da palpação de todas as cadeias linfonodais cervicais e descrever a localização, o tamanho, a consistência, a mobilidade e a presença de sinais flogísticos.\"\nEstá correto o que se afirma em:",
        "interactionType": "multiple-choice",
        "options": [
            "A) Apenas I e II estão corretas.",
            "B) Apenas I e IV estão corretas.",
            "C) Apenas II e III estão corretas.",
            "D) Apenas III e IV estão corretas.",
            "E) Todas as alternativas anteriores estão corretas."
        ],
        "gabarito": "Alternativa B (Apenas I e IV estão corretas).\n\n**COMENTÁRIO DO GABARITO:**\n\n• I — VERDADEIRO: Homem jovem, trabalhador rural procedente de área endêmica de leishmaniose/doenças infecciosas, apresentando linfadenopatia cervical com sinais flogísticos evidentes (dor, calor local, rubor, consistência elástica e flutuante com tendência a fistulização) associada a febre e odinofagia. Esses achados caracterizam linfadenite aguda infecciosa reacional (bacteriana ou micobacteriana).\n• II — FALSO: A assertiva afirma que o quadro sugere metástase de neoplasia maligna primária de orofaringe. Pelo contrário: linfonodos metastáticos caracterizam-se por evolução insidiosa e indolor, consistência endurecida/pétrea, ausência de sinais flogísticos e fixação aos planos profundos, o que é diametralmente oposto ao quadro flogístico e amolecido do caso.\n• III — FALSO: A presença de linfonodo endurecido, indolor e aderido aos planos profundos é típica de NEOPLASIA MALIGNA (metástase ou linfoma), e não de infecção bacteriana aguda.\n• IV — VERDADEIRO: A palpação de linfonodos cervicais deve ser realizada de forma sistemática e bilateral, posicionando-se preferencialmente atrás do paciente sentado, examinando as cadeias submentoniana, submandibular, tonsilar, pré e pós-auricular, occipital, cervical superficial e profunda e supraclavicular.\n• Resumo Semiológico: Apenas I e IV estão corretas (Alternativa B)."
    },
    {
        "type": "MÚLTIPLA ESCOLHA",
        "text": "Sobre o exame da glândula tireoide, analise as assertivas a seguir:\nI. A palpação pode ser realizada por via anterior ou posterior, solicitando-se ao paciente que degluta para que a glândula se desloque sob os dedos do examinador.\nII. Devem ser descritos volume, consistência, mobilidade, superfície, sensibilidade e presença de nódulos.\nIII. A ausculta da tireoide é dispensável, pois a glândula não apresenta vascularização suficiente para gerar sopros.\nIV. A presença de sopro sobre a glândula sugere hipervascularização, achado que pode ocorrer na doença de Graves.\nEstá correto o que se afirma em:",
        "interactionType": "multiple-choice",
        "options": [
            "A) Apenas I e III estão corretas.",
            "B) Apenas I, II e IV estão corretas.",
            "C) Apenas II e III estão corretas.",
            "D) Apenas III e IV estão corretas.",
            "E) Todas as alternativas estão corretas."
        ],
        "gabarito": "Alternativa B (Apenas I, II e IV estão corretas).\n\n**COMENTÁRIO DO GABARITO:**\n\n• I — VERDADEIRO: Na palpação da tireoide pela abordagem posterior (Técnica de Criley ou Quervain), o examinador posiciona-se por trás do paciente sentado, repousa os polegares na nuca e utiliza as polpas digitais dos dedos indicador e médio de ambas as mãos sobre a traqueia abaixo da cartilagem cricoide, solicitando a deglutição (a tireoide sobe junto com a laringe).\n• II — VERDADEIRO: A consistência normal do parênquima tireoidiano palpável é elástica, firme e homogênea. Consistência pétrea sugere fortemente carcinoma tireoidiano indiferenciado ou tireoidite crônica de Riedel, enquanto consistência nodular endurecida exige punção aspirativa por agulha fina (PAAF).\n• III — FALSO: A ausculta sobre os lobos tireoidianos aumentados NÃO é irrelevante nem dispensável. Pelo contrário: a detecção de um sopro contínuo sistólico-diastólico acompanhado de frêmito tátil na Doença de Graves traduz o hiperfluxo vascular exuberante da glândula hipertireóidea (bócio hipervascularizado), sendo achado semiológico de grande valor diagnóstico.\n• IV — VERDADEIRO: A glândula tireoide fixa-se à traqueia e à cartilagem cricoide pela fáscia pré-traqueal. Por conseguinte, durante o ato de deglutição voluntária ou ingestão de um gole de água, a glândula obrigatoriamente eleva-se no pescoço, o que permite distingui-la de massas cervicais estáticas ou linfonodos fixos à musculatura cervical.\n• Resumo Semiológico: Apenas I, II e IV estão corretas (Alternativa B)."
    },
    {
        "type": "DISCURSIVA",
        "text": "a. Descreva a técnica de execução dos testes de Rinne e de Weber.\nb. Explique o que cada teste compara e por que eles são considerados complementares, e não concorrentes.\nc. Complete o raciocínio para os dois cenários: (i) Weber lateraliza para a orelha direita e Rinne está negativo à direita; (ii) Weber lateraliza para a orelha esquerda e Rinne está positivo em ambas as orelhas. Indique o tipo de perda auditiva e o lado acometido em cada caso.",
        "interactionType": "textarea",
        "gabarito": "Gabarito Comentado e Completo:\n\n(a) Técnica de Execução dos Testes de Rinne e Weber:\n• Teste de Rinne:\n  1. O examinador faz vibrar as hastes de um diapasão de 512 Hz (ou 256 Hz) mediante leve toque na palma da mão ou cotovelo.\n  2. A base do diapasão é apoiada com firmeza sobre o processo mastoide do osso temporal do paciente (pesquisa da Condução Óssea - CO).\n  3. Solicita-se ao paciente que avise no exato instante em que o som deixar de ser ouvido.\n  4. Nesse momento exato, sem reativar o diapasão, as hastes vibratórias são posicionadas a 1 a 2 cm do meato acústico externo do mesmo ouvido, com as hastes paralelas ao plano da orelha (pesquisa da Condução Aérea - CA).\n  5. Pergunta-se se o paciente ainda consegue ouvir o som e por quanto tempo persiste.\n• Teste de Weber:\n  1. O examinador ativa o diapasão de 512 Hz.\n  2. A base do diapasão é firmemente apoiada no ponto central superior da cabeça do paciente (vértex craniano, linha média da fronte ou glabela, ou sobre os incisivos superiores centrais).\n  3. Pergunta-se ao paciente em qual ouvido o som vibra com maior intensidade: se no centro da cabeça igualmente em ambos os ouvidos (sem lateralização), ou se lateraliza para o ouvido direito ou esquerdo.\n\n(b) Interpretação Fisiopatológica dos Resultados:\n• Rinne Positivo (CA > CO): Situação fisiológica normal ou perda auditiva neurossensorial pura. O som na via aérea continua sendo ouvido após cessar na mastoide, pois o aparelho timpânico-ossicular amplifica eficazmente a energia sonora mecânica.\n• Rinne Negativo (CO ≥ CA): Patológico para PERDA AUDITIVA CONDUTIVA (bloqueio mecânico no canal auditivo externo ou na orelha média: rolha de cerume, perfuração timpânica, otite média secretora, otoesclerose). A via óssea supera a via aérea obstruída.\n• Weber Indiferente (Central): Normalidade ou perda neurossensorial bilateral perfeitamente simétrica.\n• Weber Lateralizado para o Ouvido Afetado (Doente): Confirma PERDA CONDUTIVA naquele ouvido (a perda do mascaramento aéreo ambiental amplifica a percepção da via óssea no lado lesionado).\n• Weber Lateralizado para o Ouvido Sadio (Oposto): Confirma PERDA NEUROSSENSORIAL no ouvido acometido (a cóclea lesada não percebe o estímulo sonoro ósseo, que é captado pela cóclea contralateral intacta)."
    },
    {
        "type": "DISCURSIVA",
        "text": "Dois pacientes chegam ao ambulatório no mesmo dia. Paciente 1: 19 anos, linfonodo cervical anterior direito de 1,0 cm, móvel, fibroelástico, doloroso, com hiperemia de orofaringe e febre de 38 °C há 3 dias. Paciente 2: 61 anos, linfonodo supraclavicular esquerdo de 3 cm, pétreo, aderido a planos profundos, indolor, com perda de 9 kg em 3 meses e sudorese noturna.\na. Para cada paciente, classifique a linfonodomegalia como provavelmente reacional ou suspeita de malignidade, justificando com pelo menos três características.\nb. Explique o que são sintomas B e por que sua presença altera a conduta.\nc. Indique a conduta apropriada para cada paciente, explicando por que a conduta oposta seria um erro em cada caso.\nd. Quais parâmetros devem obrigatoriamente constar da descrição de um linfonodo no prontuário?",
        "interactionType": "textarea",
        "gabarito": "Gabarito Comentado e Completo:\n\n(a) Hipóteses Diagnósticas dos Dois Pacientes:\n• Paciente 1 (Jovem de 19 anos com adenomegalia submandibular de 1,5 cm, móvel, consistência elástica fibrocartilaginosa, calor local, dor espontânea e à palpação, associada a febre de início súbito e dor de garganta):\n  - Hipótese Diagnóstica Primária: LINFADENOPATIA REACIONAL AGUDA INFECCIOSA (Linfadenite secundária a faringoamigdalite bacteriana ou viral).\n• Paciente 2 (Homem de 65 anos, tabagista e etilista pesado, com massa supraclavicular esquerda de 3,5 cm, indolor, pétrea, fixa e irregular, sem dor ou febre, com perda de 8 kg em 2 meses):\n  - Hipótese Diagnóstica Primária: METÁSTASE LINFONODAL NEOPLÁSICA MALIGNA (Linfonodo de Virchow / Sinal de Troisier, secundário a neoplasia maligna primária gastrointestinal gástrica/pancreática ou pulmonar/esofágica).\n\n(b) Quatro Atributos Semiológicos Comparativos que Diferenciam Processo Inflamatório de Neoplasia:\n1. Consistência:\n   - Reacional/Infeccioso: Consistência elástica ou amolecida (podendo flutuar se houver liquefação purulenta/abscesso).\n   - Neoplásico: Consistência endurecida, lígnea ou francamente PÉTREA (infiltração de células tumorais com desmoplasia estromal intensa).\n2. Mobilidade em Relação aos Planos Profundos:\n   - Reacional: Móvel, desliza livremente sob a pele e sobre os planos musculares e ósseos profundos.\n   - Neoplásico: Fixo, coalescente ou aderido intimamente aos tecidos profundos e à fáscia muscular adjacente (infiltração capsular extracelular).\n3. Sensibilidade / Dor:\n   - Reacional: Tipicamente DOLOROSO à palpação e manipulação e com dor espontânea (distensão rápida da cápsula linfonodal mediada por cininas e prostaglandinas flogísticas).\n   - Neoplásico: Caracteristicamente INDOLOR (o crescimento tumoral progressivo e insidioso não deflagra resposta inflamatória aguda capsular imediata).\n4. Sinais Inflamatórios Periféricos:\n   - Reacional: Presença marcante de eritema cutâneo (rubor), hipertermia local (calor) e edema satélite na pele sobrejacente.\n   - Neoplásico: Pele sobrejacente fria e de coloração normal (ausência de sinais flogísticos agudos), podendo haver apenas ulceração em estágios muito avançados."
    },
    {
        "type": "DISCURSIVA",
        "text": "a. Descreva a sequência do exame do pescoço, indicando o que se avalia em cada etapa.\nb. Por que a ausculta não pode ser omitida no exame do pescoço? Cite dois achados auscultatórios possíveis e seu significado.\nc. Explique como se pesquisa a turgência jugular e o que significa encontrá-la a 45°.",
        "interactionType": "textarea",
        "gabarito": "(a) Inspeção, palpação (cadeias, tireoide, pulsos carotídeos isoladamente), ausculta e mobilidade.\n(b) Para detectar sopros. Sopro carotídeo = estenose aterosclerótica. Sopro tireoidiano = Graves (hipervascularização).\n(c) Paciente em decúbito dorsal com tronco a 45°. Jugular turgida (acima da clavícula) indica pressão venosa central elevada (congestão direita)."
    },
    {
        "type": "MÚLTIPLA ESCOLHA",
        "text": "Sobre a inspeção estática e dinâmica do tórax, analise as assertivas a seguir:\nI. O tórax em tonel (ou em barril) apresenta aumento do diâmetro anteroposterior e é classicamente associado ao enfisema pulmonar.\nII. O pectus excavatum caracteriza-se por depressão da porção inferior do esterno, enquanto o pectus carinatum apresenta protrusão esternal anterior.\nIII. A respiração toracoabdominal, com predomínio da ação diafragmática, é o padrão observado principalmente no sexo feminino adulto.\nIV. O tiragem intercostal e o uso de musculatura acessória são sinais de esforço respiratório aumentado.\nEstá correto o que se afirma em:",
        "interactionType": "multiple-choice",
        "options": [
            "A) Apenas I e III estão corretas.",
            "B) Apenas I, II e IV estão corretas.",
            "C) Apenas II e III estão corretas.",
            "D) Apenas III e IV estão corretas.",
            "E) Todas as alternativas estão corretas."
        ],
        "gabarito": "Gabarito Comentado e Completo:\n\n(a) Sequência Semiológica Completa do Exame do Pescoço:\n1. Inspeção Estática e Dinâmica:\n   - Posição da cabeça (alinhada ou em torcicolo); simetria cervical; presença de abaulamentos anteriores, laterais ou fossas supraclaviculares; cicatrizes cirúrgicas (tireoidectomia); lesões de pele; turgência jugular patológica a 45°; pulsações arteriais visíveis anormais; mobilidade da linha média cervical durante a deglutição voluntária (elevação da cartilagem tireoide e cricoide).\n2. Palpação:\n   - Cadeias Linfonodais: Submentoniana, submandibulares, tonsilares, pré e retroauriculares, occipitais, cervicais superficiais e profundas (ao longo do esternocleidomastóideo) e fossas supraclaviculares.\n   - Glândula Tireoide: Posição, volume, simetria dos lobos, presença de bócio difuso ou nodular, consistência (elástica, fibroelástica ou pétrea), sensibilidade/dor e mobilidade à deglutição.\n   - Traqueia: Alinhamento na linha média cervical e mobilidade lateral, pesquisando desvios contralaterais ou ipsilaterais.\n   - Pulsos Carotídeos: Palpados no terço médio cervical, medialmente à borda anterior do ECM, avaliando simetria, amplitude, tensão e ritmo.\n3. Ausculta:\n   - Ausculta das artérias carótidas com o diafragma do estetoscópio (solicitando apneia inspiratória breve ao paciente) para detecção de sopros estenóticos carotídeos.\n   - Ausculta sobre a glândula tireoide para pesquisa de sopros vasculares e frêmitos em bócios hiperfuncionantes (Doença de Graves).\n\n(b) Dois Cuidados Mandatórios na Palpação Carotídea e suas Justificativas:\n1. NUNCA palpar ambas as artérias carótidas simultaneamente (palpar SEMPRE um lado de cada vez):\n   - Justificativa Fisiopatológica: A compressão carotídea bilateral oclui criticamente a perfusão arterial cerebral hemisférica anterior através dos polígonos de Willis, precipitando isquemia cerebral global transitória imediata, síncope e risco de hipóxia cortical grave.\n2. Evitar palpar profundamente a região superior do pescoço no nível do triângulo carotídeo (bulbo carotídeo/bifurcação junto à cartilagem tireoide), especialmente em idosos com aterosclerose:\n   - Justificativa Fisiopatológica: A compressão mecânica direta sobre os barorreceptores do seio carotídeo estimula reflexo vagal intenso (reflexo barorreceptor aferente via IX par e eferente via X par), desencadeando bradicardia sinusal súbita, assistolia temporária ou hipotensão arterial refratária (Síncope do Seio Carotídeo). Além disso, pode fragmentar e embolizar placas de ateroma carotídeas para a circulação cerebral, causando AVC isquêmico embólico."
    },
    {
        "type": "MÚLTIPLA ESCOLHA",
        "text": "Sobre avaliação do aparelho respiratório, analise as assertivas a seguir:\nI. Ao se examinar um paciente com pneumonia, espera-se que o frêmito toracovocal esteja reduzido, bem como durante a percussão espera-se um som maciço ou submaciço.\nII. Durante uma crise de asma, ao realizar a ausculta respiratória pode-se encontrar um som anormal contínuo, conhecido como sibilo.\nIII. Ao se auscultar um paciente com pneumotórax espera-se ouvir um som hipertimpânico.\nIV. Durante a percussão de um paciente com derrame pleural em hemitórax direito, espera-se ouvir um som submaciço/maciço ao percutir este hemitórax.\nAssinale a alternativa correta:",
        "interactionType": "multiple-choice",
        "options": [
            "A) Todos os itens estão corretos.",
            "B) Apenas o item I é falso.",
            "C) Apenas o item IV é verdadeiro.",
            "D) Apenas os itens II e IV são verdadeiros.",
            "E) Os itens II, III e IV são verdadeiros."
        ],
        "gabarito": "Alternativa B (Apenas I, II e IV estão corretas).\n\n**COMENTÁRIO DO GABARITO:**\n\n• I — VERDADEIRO: O tórax em tonel (ou enfisematoso) decorre do aprisionamento crônico de ar e hiperinsuflação alveolar na DPOC/enfisema, manifestando-se por aumento pronunciado do diâmetro anteroposterior do tórax, horizontalização dos arcos costais e ângulo de Charpy obtuso (> 90°).\n• II — VERDADEIRO: A tiragem intercostal consiste na retração paradoxal dos espaços intercostais e fossas supraclaviculares durante a fase inspiratória ativa. Decorre da geração de pressão intrapleural excessivamente negativa pelo esforço dos músculos inspiratórios em vencer uma resistência mecânica crítica de vias aéreas ou baixa complacência pulmonar, sendo sinal inequívoco de insuficiência respiratória iminente.\n• III — FALSO: O padrão respiratório tóraco-abdominal (com predomínio da excursão diafragmática e expansão abdominal concomitante) é o padrão fisiológico habitual em HOMENS adultos. O padrão respiratório costal superior (com predomínio da excursão dos arcos costais torácicos superiores) é o padrão fisiológico típico em MULHERES adultas.\n• IV — VERDADEIRO: A respiração paradoxal (ou dissociação tóraco-abdominal) ocorre quando o abdome retrai na inspiração (ao invés de se expandir) enquanto o tórax expande, decorrente da exaustão e paralisia do músculo diafragma, indicando falência mecânica respiratória terminal que exige intubação traqueal urgente.\n• Resumo Semiológico: Apenas I, II e IV estão corretas (Alternativa B)."
    },
    {
        "type": "MÚLTIPLA ESCOLHA",
        "text": "Sobre os ruídos adventícios da ausculta pulmonar, analise as assertivas a seguir:\nI. Os estertores finos são descontínuos, agudos, ocorrem ao final da inspiração e não se modificam com a tosse.\nII. Os roncos são ruídos contínuos e graves, originados em brônquios de maior calibre com secreção, e tipicamente se modificam ou desaparecem após a tosse.\nIII. O estridor é um ruído contínuo, de predomínio expiratório, originado em vias aéreas bronquiolares.\nIV. O atrito pleural é um ruído áspero, audível em ambas as fases respiratórias, que desaparece quando o paciente prende a respiração.\nEstá correto o que se afirma em:",
        "interactionType": "multiple-choice",
        "options": [
            "A) Apenas I e III estão corretas.",
            "B) Apenas I, II e IV estão corretas.",
            "C) Apenas II e III estão corretas.",
            "D) Apenas III e IV estão corretas.",
            "E) Todas as alternativas estão corretas."
        ],
        "gabarito": "Alternativa D (Apenas II e IV estão corretas).\n\n**COMENTÁRIO DO GABARITO:**\n\n• I — FALSO: Na pneumonia comunitária com consolidação parenquimatosa lobar típica (espaço alveolar preenchido por exsudato inflamatório denso com brônquios pérvios), a transmissão das ondas sonoras originadas na laringe encontra um meio sólido altamente transmissor, resultando em Frêmito Toracovocal (FTV) MARCADAMENTE AUMENTADO, e não abolido. O FTV abolido ocorre em atelectasias com brônquio ocluído, pneumotórax ou derrame pleural.\n• II — VERDADEIRO: A percussão do tórax sobre o parênquima pulmonar normal preenchido por ar e septos alveolares finos produz som claro atimpânico (som claro pulmonar fisiológico).\n• III — FALSO: O derrame pleural volumoso produz macicez absoluta à percussão torácica na região do derrame (líquido interposto), enquanto a área pulmonar colapsada imediatamente superior pode apresentar submacicez. O som atimpânico é o som pulmonar fisiológico normal, e o hipertimpanismo surge quando há ar livre sob tensão (pneumotórax ou hiperinsuflação).\n• IV — VERDADEIRO: A pesquisa da expansibilidade dos ápices e das bases pulmonares é realizada através da Manobra de Rouault (nos ápices torácicos) e da Manobra de Lasègue/Bases (com os polegares do examinador aproximados na linha média paravertebral dorsal ao nível da 10ª costela, solicitando inspiração profunda do paciente).\n• Resumo Semiológico: Apenas II e IV estão corretas (Alternativa D)."
    },
    {
        "type": "MÚLTIPLA ESCOLHA",
        "text": "O exame do aparelho respiratório é de grande importância na prática médica. Acerca desse exame, analise as assertivas a seguir:\nI. Pacientes com enfisema pulmonar apresentam frequentemente alargamento da porção inferior do tórax, como a boca de um sino, lembrando um cone de base inferior.\nII. A respiração costal superior, observada principalmente no sexo masculino, deve-se ao predomínio da ação dos músculos escaleno e esternocleidomastóideo.\nIII. Pacientes com quadro de redução de calibre da laringe e/ou da traqueia apresentam sibilos, decorrentes da obstrução das vias respiratórias altas, como na laringite aguda, câncer de laringe e estenose de traqueia.\nIV. Paciente com sons de frequência alta (agudos) no final da inspiração, que se alteram com a mudança de posição e não se alteram com a tosse: os sons descritos são os estertores grossos.\nV. Pacientes com derrame pleural volumoso à direita apresentam redução do frêmito toracovocal à palpação e submacicez ou macicez à percussão do hemitórax direito.\nEstá correto o que se afirma em:",
        "interactionType": "multiple-choice",
        "options": [
            "A) Apenas I e V estão corretas.",
            "B) Apenas II e III estão corretas.",
            "C) Apenas I, III e V estão corretas.",
            "D) Apenas II, IV e V estão corretas.",
            "E) Todas as alternativas estão corretas."
        ],
        "gabarito": "Alternativa B (Apenas I, II e IV estão corretas).\n\n**COMENTÁRIO DO GABARITO:**\n\n• I — VERDADEIRO: Os sibilos são ruídos adventícios contínuos, musicais e agudos, decorrentes da passagem turbilhonar de ar em alta velocidade através de bronquíolos estreitados difusamente por broncoespasmo, edema de mucosa ou secreções aderentes (típicos de asma brônquica e exacerbação de DPOC).\n• II — VERDADEIRO: Os estertores finos (ou crepitantes) são ruídos adventícios descontínuos, curtos e explosivos, que ocorrem tipicamente no final da fase inspiratória (teleinspiratórios). Resultam da abertura súbita e estalante de alvéolos e bronquíolos terminais que estavam previamente colapsados por líquido exsudativo ou aumento da tensão superficial (pneumonia, congestão pulmonar cardiogênica, fibrose pulmonar). Não se modificam com a tosse.\n• III — FALSO: O estridor é um ruído inspiratório contínuo, áspero e de alta frequência audível frequentemente à distância sem estetoscópio, decorrente da obstrução mecânica crítica ou estenose de vias aéreas SUPERIORES e extratorácicas (laringe, epiglote e traqueia alta: laringotraqueíte, aspiração de corpo estranho, edema de glote por anafilaxia), e NÃO de bronquíolos distais.\n• IV — VERDADEIRO: O atrito pleural é um ruído descontínuo ou contínuo, de tonalidade áspera semelhante ao atrito de couro ressecado ou pisar na neve fresca, produzido pelo roçar recíproco dos folhetos pleurais parietal e visceral espessados e inflamados na pleurite aguda. É audível tanto na inspiração quanto na expiração e desaparece se houver acúmulo de derrame pleural volumoso separando os folhetos.\n• Resumo Semiológico: Apenas I, II e IV estão corretas (Alternativa B)."
    },
    {
        "type": "MÚLTIPLA ESCOLHA",
        "text": "Adolescente de 18 anos, longilíneo, alto e magro, apresenta dor torácica súbita \"em punhalada\" à direita e dispneia progressiva, iniciadas há 2 horas, sem trauma e sem febre. Ao exame do hemitórax direito: expansibilidade reduzida, frêmito toracovocal abolido, hipertimpanismo à percussão e murmúrio vesicular abolido. A traqueia encontra-se desviada para a esquerda e há turgência jugular. O diagnóstico e a implicação mais provável são:",
        "interactionType": "multiple-choice",
        "options": [
            "A) Derrame pleural à direita; a macicez confirma o acúmulo de líquido.",
            "B) Pneumonia lobar à direita; o frêmito abolido decorre da consolidação.",
            "C) Pneumotórax hipertensivo à direita; trata-se de emergência, pelo desvio de mediastino e comprometimento do retorno venoso.",
            "D) Atelectasia do lobo médio direito; o desvio traqueal contralateral confirma a retração.",
            "E) Crise asmática grave; o hipertimpanismo decorre da hiperinsuflação bilateral."
        ],
        "gabarito": "Alternativa A (Apenas as afirmativas I e V estão corretas).\n\n**COMENTÁRIO DO GABARITO:**\n\n• I — VERDADEIRO: A ausculta da voz através do estetoscópio sobre uma zona de pulmão consolidado (pneumonia lobar) transmite as palavras faladas com clareza nítida e timbre agudo preservado (Broncofonia ou Pectorilóquia), decorrente do aumento de condução sonora pelo tecido parenquimatoso adensado.\n• II — FALSO: O padrão respiratório tóraco-abdominal é característico de indivíduos do sexo masculino. O padrão costal superior é característico do sexo feminino.\n• III — FALSO: O atrito pleural NÃO é provocado por secreção em brônquios de grande calibre (isso produz roncos). O atrito decorre do atrito mecânico direto entre os folhetos pleurais inflamados (pleura visceral e parietal).\n• IV — FALSO: No pneumotórax (ar no espaço pleural), a percussão torácica revela HIPERTIMPANISMO (som excessivamente ressonante e oco pela coluna de gás sob tensão), e nunca macicez (macicez é típica de líquido/derrame ou consolidação sólida).\n• V — VERDADEIRO: A tosse seca (irritativa, sem secreção) costuma originar-se de irritação das vias aéreas superiores, pleura, uso de IECA ou neoplasias broncogênicas iniciais; enquanto a tosse produtiva com expectoração mucopurulenta reflete infecção bacteriana ativa de vias aéreas baixas (bronquite, pneumonia, bronquiectasias).\n• Resumo Semiológico: Apenas I e V estão corretas (Alternativa A)."
    },
    {
        "type": "MÚLTIPLA ESCOLHA",
        "text": "Um paciente de 33 anos comparece para atendimento de emergência devido a quadro de febre alta, tosse produtiva (escarro amarelado) e dispneia iniciados há 48 horas. Não há histórico de comorbidades. Ao exame físico: estado geral regular, respiração dispneica, FR = 28 irpm, FC = 110 bpm, PA = 118x76 mmHg, pulso radial cheio e taquisfígmico, temperatura axilar = 38,8 °C. Ao exame do aparelho respiratório, percebe-se em terço inferior de hemitórax direito diminuição da expansibilidade pulmonar, frêmito toracovocal aumentado, submacicez à percussão, estertores finos à ausculta pulmonar e broncofonia. O diagnóstico mais provável é:",
        "interactionType": "multiple-choice",
        "options": [
            "A) Pneumotórax",
            "B) Atelectasia",
            "C) Pleurite aguda",
            "D) Pneumonia bacteriana",
            "E) Derrame pleural"
        ],
        "gabarito": "Alternativa C.\n\n**COMENTÁRIO DO GABARITO:**\n\n• Perfil Clínico e Fisiopatologia: Adolescente de 18 anos, biotipo longilíneo (alto e magro), apresentando dor torácica pleurítica súbita associada a dispneia aguda em hemitórax direito. O exame revela abolição do murmúrio vesicular, abolição do frêmito toracovocal, HIPERTIMPANISMO à percussão em todo o hemitórax direito, associado a DESVIO DA TRAQUEIA PARA A ESQUERDA (lado contralateral), hipotensão e taquicardia.\n• Diagnóstico Sindrômico e Gravidade: Trata-se de um PNEUMOTÓRAX HIPERTENSIVO À DIREITA (decorrente da ruptura espontânea de bleb subpleural apical com formação de mecanismo valvular unidirecional: o ar entra no espaço pleural na inspiração mas não sai na expiração).\n• A pressão intrapleural positiva progressiva colapsa totalmente o pulmão direito, comprime o mediastino e as veias cavas e empurra a traqueia e o coração para o hemitórax contralateral, comprometendo drasticamente o retorno venoso cardíaco e o débito sistólico, gerando choque obstrutivo circulatório com hipotensão e risco iminente de parada cardiorrespiratória.\n• Conduta Emergencial: Descompressão torácica imediata por toracocentese com agulha no 2º EIC na linha hemiclavicular ou 5º EIC na linha axilar anterior/média, sem aguardar exame radiológico (Alternativa C)."
    },
    {
        "type": "MÚLTIPLA ESCOLHA",
        "text": "Mulher de 71 anos, com insuficiência cardíaca, apresenta dispneia progressiva há duas semanas. Ao exame do hemitórax esquerdo: expansibilidade reduzida em terço inferior, frêmito toracovocal abolido, macicez à percussão até a altura do ângulo inferior da escápula e murmúrio vesicular abolido nessa região. Analise as assertivas:\nI. O conjunto frêmito abolido + macicez + murmúrio abolido é compatível com derrame pleural.\nII. A presença de frêmito abolido afasta a hipótese de síndrome de consolidação nessa região.\nIII. Caso houvesse desvio da traqueia, seria esperado desvio para o lado direito, por se tratar de processo expansivo.\nIV. Na borda superior do derrame pode-se auscultar sopro pleurítico, decorrente da compressão do parênquima pulmonar adjacente.\nEstá correto o que se afirma em:",
        "interactionType": "multiple-choice",
        "options": [
            "A) Apenas I e II estão corretas.",
            "B) Apenas I, II e III estão corretas.",
            "C) Apenas II e IV estão corretas.",
            "D) Apenas III e IV estão corretas.",
            "E) Todas as alternativas estão corretas."
        ],
        "gabarito": "Alternativa D.\n\n**COMENTÁRIO DO GABARITO:**\n\n• A combinação dos achados propedêuticos:\n  1. Febre alta aguda com tosse e escarro mucopurulento (\"ferruginoso\");\n  2. Expansibilidade torácica reduzida no lobo inferior afetado;\n  3. Frêmito toracovocal (FTV) MARCADAMENTE AUMENTADO;\n  4. Submacicez / macicez à percussão torácica localizada;\n  5. Murmúrio vesicular substituído por sopro tubário / respiração brônquica e presença de estertores finos teleinspiratórios crepitantes;\n  6. Pectorilóquia fônica evidente (voz auscultada perfeitamente nítida);\n• Esse agrupamento semiológico compõe a clássica SÍNDROME DE CONSOLIDAÇÃO PULMONAR, cujo exemplo mais representativo na prática médica de emergência é a PNEUMONIA BACTERIANA lobar aguda (Alternativa D).\n• No pneumotórax (A) haveria hipertimpanismo e FTV abolido; na atelectasia (B) o FTV estaria reduzido com retração traqueal ipsilateral; no derrame pleural (E) o FTV estaria abolido com macicez e linha de Damoiseau."
    },
    {
        "type": "VERDADEIRO OU FALSO",
        "text": "Sobre o frêmito toracovocal e a percussão do tórax, assinale V ou F e marque a sequência correta:\nI. O frêmito toracovocal é pesquisado com a face ulnar ou a palma das mãos, solicitando-se ao paciente que repita uma expressão padronizada, como \"trinta e três\".\nII. O som claro pulmonar é o som normal obtido à percussão do tórax de um indivíduo hígido.\nIII. A macicez indica substituição do ar por líquido ou tecido sólido, enquanto o timpanismo indica excesso de ar.\nIV. Na síndrome de consolidação o frêmito está reduzido porque o exsudato alveolar dificulta a transmissão das vibrações.\nV. A percussão do tórax deve ser realizada de forma comparativa entre hemitórax homólogos, de cima para baixo.\nMarque a alternativa que representa a sequência correta:",
        "interactionType": "multiple-choice",
        "options": [
            "A) V – V – V – F – V",
            "B) V – F – V – V – F",
            "C) F – V – V – F – V",
            "D) V – V – F – F – V",
            "E) F – F – V – V – V"
        ],
        "gabarito": "Alternativa E (Todas as assertivas estão corretas).\n\n**COMENTÁRIO DO GABARITO:**\n\n• I — VERDADEIRO: O acúmulo de líquido livre no espaço pleural afasta a superfície pulmonar da parede torácica e atua como uma barreira acústica de impedância mecânica extrema, extinguindo a propagação sonora da laringe até o tórax e resultando na redução acentuada ou abolição completa do frêmito toracovocal (FTV abolido) na base pulmonar comprometida.\n• II — VERDADEIRO: O líquido denso preenchendo o espaço pleural substitui o parênquima pulmonar aéreo elástico por um meio hídrico incompressível, produzindo som maciço (macicez à percussão) cuja linha limitante superior descreve classicamente uma curva de concavidade voltada para cima e para dentro (Linha ou Curva de Damoiseau-Ellis).\n• III — VERDADEIRO: O murmúrio vesicular fisiológico desaparece na topografia do derrame pleural líquido (abolição do MV na base). Imediatamente acima do nível do derrame, o pulmão subjacente sofre atelectasia compressiva, gerando transmissão brônquica anômala com sopro pleurítico e egofonia (voz anasalada e metálica com som de \"balido de cabra\" - conversão do som de \"E\" falado em som de \"A\" auscultado).\n• IV — VERDADEIRO: O hemitórax acometido pelo derrame volumoso apresenta assimetria com hipoexpansibilidade evidente durante a inspeção dinâmica e na manobra bimanual de bases, decorrente da restrição mecânica imposta pela coleção líquida intratorácica.\n• Resumo Semiológico: Todas as afirmativas são verdadeiras (Alternativa E)."
    },
    {
        "type": "DISCURSIVA",
        "text": "a. Construa um quadro comparativo entre síndrome de consolidação, derrame pleural e pneumotórax, contemplando: expansibilidade, frêmito toracovocal, percussão e ausculta.\nb. Explique o mecanismo físico pelo qual o frêmito aumenta na consolidação e diminui no derrame pleural.\nc. Um estudante afirma: \"encontrei submacicez à percussão, logo trata-se de derrame pleural\". Corrija a afirmação e indique qual achado deve ser usado para desempatar.",
        "interactionType": "textarea",
        "gabarito": "Alternativa A (Sequência: V – V – V – F – V).\n\n**COMENTÁRIO DO GABARITO:**\n\n• (V) O frêmito toracovocal (FTV) pesquisa a transmissão palpatória das vibrações da laringe através da coluna aérea traqueobrônquica até a parede torácica, solicitando-se ao paciente que pronuncie repetidamente palavras ressonantes ricas em consoantes nasais e líquidas (ex.: \"trinta e três\"), apoiando-se a face palmar ou borda ulnar da mão espalmada simetricamente sobre ambos os hemitórax.\n• (V) No pneumotórax volumoso, a interposição de ar livre e compressão do pulmão reduz a condução vibratória da voz, resultando em FTV totalmente abolido, acompanhado de hipertimpanismo acentuado à percussão torácica.\n• (V) A presença de condensação pulmonar com brônquios pérvios (pneumonia lobar) aumenta consideravelmente a densidade do parênquima, facilitando a transmissão do som da laringe e gerando FTV marcadamente aumentado sobre a lesão.\n• (F) A assertiva afirma que \"na consolidação pulmonar o frêmito toracovocal encontra-se abolido\". É FALSO: na consolidação pulmonar o FTV está AUMENTADO (hiperfonético/hiperfrêmito), e não abolido. Quem abole o frêmito é o derrame pleural, o pneumotórax e a atelectasia obstrutiva.\n• (V) A percussão com dígito-pressão pleximétrica sobre o hemitórax acometido por derrame pleural volumoso produz som maciço característico (macicez hídrica absoluta).\n• Resumo Semiológico: Sequência correta: V – V – V – F – V (Alternativa A)."
    },
    {
        "type": "DISCURSIVA",
        "text": "Homem de 62 anos, tabagista de longa data, procura o pronto-socorro com dispneia progressiva há 3 dias e tosse com expectoração esverdeada. Ao exame: FR = 30 irpm, uso de musculatura acessória, tórax em tonel, hipersonoridade difusa à percussão, murmúrio vesicular globalmente diminuído e sibilos expiratórios difusos. SpO₂ = 86% em ar ambiente.\na. Descreva o que significa cada achado do exame físico encontrado e a que alteração fisiopatológica ele corresponde.\nb. Explique por que o tórax em tonel e a hipersonoridade difusa apontam para doença crônica, e não para o quadro agudo dos últimos 3 dias.\nc. Se, durante a evolução, os sibilos desaparecessem e o murmúrio vesicular se tornasse quase inaudível, isso indicaria melhora ou piora? Justifique.\nd. Calcule a carga tabágica presumida se o paciente fumar 1,5 maço/dia há 40 anos.",
        "interactionType": "textarea",
        "gabarito": "Gabarito Comentado e Completo:\n\n(a) Quadro Comparativo Semiológico entre as Três Grandes Síndromes Respiratórias:\n\n| Parâmetro Semiológico | Síndrome de Consolidação (Pneumonia) | Derrame Pleural Volumoso | Pneumotórax Volumoso |\n| :--- | :--- | :--- | :--- |\n| **Expansibilidade** | Diminuída no hemitórax/lobo afetado | Diminuída no hemitórax afetado | Diminuída ou ausente no lado afetado |\n| **Frêmito Toracovocal (FTV)** | **AUMENTADO** (condensação sólida facilita propagação) | **ABOLIDO** ou acentuadamente diminuído (líquido bloqueia) | **ABOLIDO** ou acentuadamente diminuído (ar livre bloqueia) |\n| **Percussão Torácica** | **Macicez / Submacicez** (tecido adensado sem ar) | **Macicez absoluta** (líquido com Curva de Damoiseau) | **HIPERTIMPANISMO** (ar sob pressão / som timpânico) |\n| **Murmúrio Vesicular (MV)** | Diminuído ou abolido, substituído por **Sopro Tubário** | **ABOLIDO** na área do derrame (líquido interposto) | **ABOLIDO** em todo o hemitórax acometido |\n| **Ruídos Adventícios** | **Estertores finos teleinspiratórios** (crepitantes); atrito pleural inicial | Ausentes no derrame; atrito pleural precoce; egofonia no limite superior | Ausentes (silêncio auscultatório completo no hemitórax) |\n| **Ressonância Vocal / Voz** | **Broncofonia aumentada e Pectorilóquia fônica/afônica** | Diminuída/abolida na base; **Egofonia** na borda superior | Diminuída ou totalmente abolida |\n\n(b) Justificativa Biofísica do Comportamento do FTV:\n• Consolidação: A substituição do ar alveolar por exsudato inflamatório denso celular cria continuidade acústica sólida entre os brônquios e a parede torácica. O meio sólido/celular conduz ondas sonoras mecânicas com velocidade e amplitude muito superiores ao ar aerado, amplificando o FTV.\n• Derrame Pleural: O líquido acumulado no espaço interfolhetar pleural afasta o pulmão da parede e impõe uma drástica descontinuidade de impedância acústica (ar-líquido-osso), refratando e dissipando as ondas vibratórias, impedindo sua transmissão até a palma da mão do examinador (FTV abolido)."
    },
    {
        "type": "DISCURSIVA",
        "text": "a. Descreva, em ordem, as quatro etapas do exame do aparelho respiratório e o que se busca em cada uma.\nb. Explique por que, no aparelho respiratório, a ordem é inspeção → palpação → percussão → ausculta, enquanto no abdome a ausculta é antecipada.\nc. Descreva a técnica de pesquisa da expansibilidade torácica e o que significa encontrá-la assimétrica.\nd. Diferencie broncofonia, pectorilóquia e egofonia, indicando o que têm em comum.",
        "interactionType": "textarea",
        "gabarito": "Gabarito Comentado e Completo:\n\n(a) As Quatro Etapas Ordenadas do Exame do Aparelho Respiratório e seus Objetivos Semiológicos:\n1. Inspeção:\n   - Inspeção Estática: Forma e conformação da caixa torácica (tórax normal, tonel/enfisematoso, cifoescoliótico, pectus excavatum, carinatum); simetria torácica; abaulamentos e retrações intercostais; lesões cutâneas e cicatrizes.\n   - Inspeção Dinâmica: Padrão/tipo respiratório (costal superior, tóraco-abdominal); frequência respiratória (eupneia, taquipneia, bradipneia); ritmo respiratório (Kussmaul, Cheyne-Stokes, Biot); amplitude das incursões; sinais de esforço ventilatório (tiragem intercostal, uso de musculatura acessória, batimento de asa nasal).\n2. Palpação:\n   - Pesquisa de dor, creptação óssea (fraturas costais) e enfisema subcutâneo;\n   - Avaliação da expansibilidade torácica nos ápices (Manobra de Rouault) e nas bases pulmonares (Manobra das Bases de Lasègue com pinçamento cutâneo na 10ª vértebra torácica);\n   - Pesquisa do Frêmito Toracovocal (FTV) sistemática e comparativa em todas as regiões dos hemitórax anterior, lateral e posterior durante a fala repetida do \"33\".\n3. Percussão:\n   - Percussão dígito-digital (técnica pleximétrica de Gerhardt) comparando pontos simétricos de ambos os hemitórax, de cima para baixo.\n   - Avaliação dos sons obtidos: Som claro atimpânico/pulmonar normal; Som maciço/submaciço (derrames pleurais e consolidações); Som timpânico/hipertimpânico (pneumotórax e hiperinsuflação).\n4. Ausculta:\n   - Avaliação com o estetoscópio do som respiratório fisiológico (murmúrio vesicular periférico, respiração broncovesicular e sopro glótico laringotraqueal);\n   - Identificação de Ruídos Adventícios Contínuos (sibilos, roncos, estridor) e Descontínuos (estertores finos crepitantes, estertores grossos bolhosos, atrito pleural);\n   - Ausculta da ressonância vocal (broncofonia, pectorilóquia e egofonia).\n\n(b) Por que a Ausculta deve ser Sempre Comparativa e Simétrica e Seguir a Respiração Completa:\n• Comparativa e Simétrica: O exame deve comparar sistematicamente o mesmo ponto anatômico do hemitórax direito com o ponto homólogo do hemitórax esquerdo antes de descer para o nível seguinte. Isso permite utilizar o pulmão sadio do próprio paciente como controle acústico de referência individual, detectando assimetrias sutis de intensidade, timbre ou ruídos adventícios localizados em um lobo pulmonar.\n• Ciclo Respiratório Completo (Inspiração e Expiração Plenas): Certos ruídos adventícios têm comportamento temporal estritamente fase-específico: os estertores finos crepitantes surgem exclusivamente no final da inspiração (teleinspiratórios); os sibilos podem ser auscultados apenas na expiração forçada; e o atrito pleural ocorre nos dois tempos. Auscultar de forma apressada sem esperar a transição dos tempos respiratórios induz a falso-negativos diagnósticos graves."
    },
    {
        "type": "DISCURSIVA",
        "text": "a. Classifique os ruídos adventícios em contínuos e descontínuos, citando exemplos de cada grupo.\nb. Diferencie estertores finos de estertores grossos quanto a timbre, momento do ciclo respiratório, local de origem e comportamento após a tosse.\nc. Diferencie sibilo de estridor quanto ao local de origem e à fase respiratória de predomínio, e explique por que essa distinção muda a urgência da abordagem.\nd. Como se diferencia, à beira do leito, um atrito pleural de um atrito pericárdico?",
        "interactionType": "textarea",
        "gabarito": "Gabarito Comentado e Completo:\n\n(a) Classificação dos Ruídos Adventícios em Contínuos e Descontínuos:\n• Ruídos Adventícios Contínuos: São sons pulmonares anormais de longa duração (> 250 milissegundos), com qualidade acústica musical ou ruidosa constante, resultantes da passagem contínua de fluxo aéreo através de vias aéreas estreitadas:\n  1. Sibilos: Agudos, sibilantes, musicais, decorrentes de broncoespasmo ou edema em bronquíolos de pequeno calibre (ex.: asma brônquica, bronquiolite).\n  2. Roncos: Graves, roucos, rudes, semelhantes a um ronco ou murmúrio baixo, originados da passagem de ar por brônquios de grande e médio calibre ocluídos por secreções mucosas espessas (ex.: bronquite aguda/crônica).\n  3. Estridor: Muito agudo, áspero e estridente, audível predominantemente na inspiração na laringe/traqueia, secundário à estenose mecânica aguda de via aérea extratorácica (ex.: laringite estridulosa, aspiração de corpo estranho).\n• Ruídos Adventícios Descontínuos: São sons curtos, explosivos, intermitentes e não musicais (< 20 milissegundos), provocados por abertura súbita de alvéolos colapsados ou por bolhas de gás explodindo em meio líquido:\n  1. Estertores Finos (Crepitantes): Secos, curtos, agudos, teleinspiratórios (ex.: pneumonia, congestão pulmonar, fibrose intersticial).\n  2. Estertores Grossos (Subcrepitantes ou Bolhosos): Graves, úmidos, holoinspiratórios e expiratórios (ex.: bronquiectasias, edema agudo de pulmão fase alveolar avançada).\n\n(b) Diferenciação Completa entre Estertores Finos e Grossos:\n\n| Característica Semiológica | Estertores Finos (Crepitantes) | Estertores Grossos (Subcrepitantes/Bolhosos) |\n| :--- | :--- | :--- |\n| **Mecanismo Fisiopatológico** | Abertura súbita e explosiva de alvéolos e bronquíolos terminais colapsados por líquido ou perda de complacência no final da inspiração | Passagem do ar em turbilhão rompendo bolhas de secreção líquida acumulada no lúmen de brônquios de médio e grande calibre |\n| **Momento no Ciclo Respiratório** | **Final da Inspiração (Teleinspiratórios)** | **Início/Meio da Inspiração e durante a Expiração (Holo)** |\n| **Timbre e Frequência Sonora** | Agudos, secos, homogêneos, semelhantes ao atrito de mecha de cabelo perto do ouvido ou descolamento de velcro | Graves, rudes, úmidos, borbulhantes, heterogêneos |\n| **Modificação com a Tosse** | **NÃO se alteram nem desaparecem com a tosse** (o colapso alveolar periférico independe da tosse) | **MODIFICAM-SE ou desaparecem temporariamente com a tosse** e expectoração (mobilização da secreção brônquica) |\n| **Condições Clínicas Típicas** | Pneumonia em fase de condensação inicial/resolução, Insuficiência Cardíaca congestiva inicial, Fibrose Pulmonar Idiopática | Bronquites agudas e crônicas, Bronquiectasias infectadas, Edema Agudo de Pulmão avançado com transudação brônquica |"
    },
    {
        "type": "MÚLTIPLA ESCOLHA",
        "text": "Sobre a inspeção, a palpação e os focos de ausculta do precórdio, analise as assertivas a seguir:\nI. O ictus cordis normal localiza-se no 5º espaço intercostal esquerdo, aproximadamente 1 cm medial à linha hemiclavicular, com extensão de até duas polpas digitais.\nII. O foco aórtico acessório, ou ponto de Erb, situa-se no 3º espaço intercostal esquerdo, junto à borda esternal, e é onde melhor se ausculta o sopro da insuficiência aórtica.\nIII. O foco mitral corresponde ao 2º espaço intercostal direito, junto à borda esternal.\nIV. Frêmito cardíaco é a tradução palpatória de um sopro de grande intensidade, correspondendo, na escala de Levine, a sopros de grau igual ou superior a 4/6.\nEstá correto o que se afirma em:",
        "interactionType": "multiple-choice",
        "options": [
            "A) Apenas I e III estão corretas.",
            "B) Apenas I, II e IV estão corretas.",
            "C) Apenas II e III estão corretas.",
            "D) Apenas III e IV estão corretas.",
            "E) Todas as alternativas estão corretas."
        ],
        "gabarito": "Alternativa B (Apenas I, II e IV estão corretas).\n\n**COMENTÁRIO DO GABARITO:**\n\n• I — VERDADEIRO: O ictus cordis (choque da ponta) em indivíduos adultos normolíneos localiza-se fisiologicamente no 4º ou 5º espaço intercostal esquerdo (EIC), na linha hemiclavicular esquerda (LHC), ocupando uma área de 1 a 2 polpas digitais (cerca de 2 a 2,5 cm de diâmetro), com amplitude e duração normais.\n• II — VERDADEIRO: Na cardiomegalia por sobrecarga de volume e dilatação ventricular esquerda (ex.: insuficiência aórtica severa, insuficiência mitral grave, miocardiopatia dilatada), o ictus cordis desloca-se para baixo e para a esquerda (ex.: 6º EIC na linha axilar anterior), tornando-se difuso (> 3 cm) e propulsivo.\n• III — FALSO: A assertiva afirma que o foco mitral localiza-se no 2º espaço intercostal direito. Isso é ABSOLUTAMENTE FALSO. O foco auscultatório localizado no 2º espaço intercostal direito junto à borda esternal é o FOCO AÓRTICO. O FOCO MITRAL localiza-se no ápice cardíaco (no 4º ou 5º EIC esquerdo na linha hemiclavicular, sobre o ictus cordis).\n• IV — VERDADEIRO: A manobra de Pachon (pesquisa do ictus cordis e ausculta em decúbito lateral esquerdo) aproxima o ápice do ventrículo esquerdo da parede torácica anterior, sendo a manobra de eleição para palpar ictus pouco perceptíveis e auscultar com a campânula o ruído de B3, B4 e o sopro em ruflar diastólico da estenose mitral.\n• Resumo Semiológico: Apenas I, II e IV estão corretas (Alternativa B)."
    },
    {
        "type": "MÚLTIPLA ESCOLHA",
        "text": "A ausculta cardíaca é um elemento da semiotécnica que possui grande relevância porque pode fornecer informações essenciais para elaboração de hipóteses diagnósticas. Considerando o exame do aparelho cardiovascular, analise as assertivas a seguir:\nI. A terceira bulha (B3) é um som de baixa frequência, sendo melhor audível com a campânula. A terceira bulha está relacionada ao momento da contração atrial.\nII. É o componente aórtico da segunda bulha cardíaca (B2) que atrasa durante o desdobramento fisiológico de B2.\nIII. A quarta bulha (B4), quando presente, localiza-se na telediástole do ciclo cardíaco e tem associação com corações com baixa complacência.\nEstá correto o que se afirma em:",
        "interactionType": "multiple-choice",
        "options": [
            "A) I, II e III estão incorretas",
            "B) Apenas I e II estão corretas",
            "C) Apenas I e III estão corretas",
            "D) Apenas II e III estão corretas",
            "E) Nenhuma das alternativas anteriores"
        ],
        "gabarito": "Alternativa E (Nenhuma das alternativas anteriores está correta).\n\n**COMENTÁRIO DO GABARITO:**\n\n• I — FALSO: A primeira parte da assertiva é correta (B3 é som de baixa frequência, melhor audível com a campânula). Porém, o erro fatal está na causa: a Terceira Bulha (B3) surge no início da diástole (PROTODIÁSTOLE), decorrendo da desaceleração abrupta do fluxo sanguíneo durante a fase de ENCHIMENTO VENTRICULAR RÁPIDO PASSIVO em um ventrículo com volume residual elevado ou parede dilatada. O ruído que decorre da contração atrial é a Quarta Bulha (B4), e não a B3.\n\n• II — FALSO: Durante a inspiração profunda fisiológica, o aumento do retorno venoso para as cavidades direitas prolonga o tempo de esvaziamento ejetivo do ventrículo direito, atrasando o fechamento da valva pulmonar. Portanto, é o componente PULMONAR (P2) que se atrasa durante o desdobramento fisiológico de B2 (afastando-se de A2), e NÃO o componente aórtico (A2 que se mantém praticamente fixo ou ligeiramente antecipado).\n\n• III — VERDADEIRO: A Quarta Bulha (B4) ocorre na telediástole (pré-sístole), exatamente no momento da contração atrial (\"patada atrial\"), quando o átrio ejeta sangue sob alta pressão contra uma parede ventricular endurecida, hipertrofiada e de baixa complacência (sobrecarga de pressão: cardiopatia hipertensiva, estenose aórtica, miocardiopatia hipertrófica).\n\n• Julgamento das Alternativas:\n  - Apenas o item III é correto.\n  - As alternativas A (\"I, II e III incorretas\"), B (\"Apenas I e II corretas\"), C (\"Apenas I e III corretas\") e D (\"Apenas II e III corretas\") são todas incorretas.\n  - Portanto, a única opção correta é a Alternativa E (Nenhuma das alternativas anteriores)."
    },
    {
        "type": "MÚLTIPLA ESCOLHA",
        "text": "Sobre as bulhas cardíacas e os ruídos acessórios, analise as assertivas a seguir:\nI. A primeira bulha (B1) resulta do fechamento das valvas mitral e tricúspide e marca o início da sístole ventricular.\nII. A terceira bulha (B3) pode ser um achado fisiológico em crianças e adultos jovens, sem significar doença.\nIII. A quarta bulha (B4) pode ser auscultada em pacientes com fibrilação atrial, pois independe da contração atrial efetiva.\nIV. O estalido de abertura é um som protodiastólico de alta frequência, classicamente associado à estenose mitral.\nEstá correto o que se afirma em:",
        "interactionType": "multiple-choice",
        "options": [
            "A) Apenas I e III estão corretas.",
            "B) Apenas I, II e IV estão corretas.",
            "C) Apenas II e III estão corretas.",
            "D) Apenas III e IV estão corretas.",
            "E) Todas as alternativas estão corretas."
        ],
        "gabarito": "Alternativa B (Apenas I, II e IV estão corretas).\n\n**COMENTÁRIO DO GABARITO:**\n\n• I — VERDADEIRO: A primeira bulha cardíaca (B1) marca o início da sístole ventricular mecânica, resultando primordialmente das vibrações geradas pelo fechamento das valvas atrioventriculares (componente mitral M1 e tricúspide T1), sendo auscultada com maior intensidade no ápice cardíaco (focos mitral e tricúspide).\n• II — VERDADEIRO: A segunda bulha cardíaca (B2) marca o final da sístole e o início da diástole mecânica ventricular, resultando do fechamento das valvas semilunares (componente aórtico A2 e pulmonar P2), sendo auscultada com intensidade máxima na base cardíaca (focos aórtico e pulmonar).\n• III — FALSO: A assertiva afirma que a B4 ocorre independentemente da contração atrial e pode estar presente na fibrilação atrial. Isso é TOTALMENTE FALSO. A B4 é rigorosamente gerada pelo impacto hemodinâmico da SÍSTOLE ATRIAL efetiva contra o ventrículo rígido. Na fibrilação atrial (FA), os átrios despolarizam de forma desorganizada e caótica (não há sístole mecânica coordenada do átrio); portanto, é ANATOMICAMENTE E FISIOLOGICAMENTE IMPOSSÍVEL existir Quarta Bulha (B4) em pacientes com fibrilação atrial.\n• IV — VERDADEIRO: A B3 pode ser um achado fisiológico e normal em crianças, adolescentes, adultos jovens saudáveis até os 35–40 anos e em gestantes no 3º trimestre (por circulação hiperdinâmica). Entretanto, quando auscultada em indivíduos com idade > 40 anos, hipertensos ou coronariopatas, assume caráter invariavelmente patológico, indicando disfunção sistólica ventricular esquerda e elevação da pressão de enchimento do VE.\n• Resumo Semiológico: Apenas I, II e IV estão corretas (Alternativa B)."
    },
    {
        "type": "MÚLTIPLA ESCOLHA",
        "text": "Analise as assertivas a seguir:\nI. Pacientes com estenose aórtica ou hipertensão arterial costumam apresentar ictus cordis difuso à inspeção do aparelho cardiovascular, enquanto pacientes com insuficiência aórtica grave em geral apresentam ictus cordis propulsivo.\nII. Paciente de 25 anos, há 3 dias evoluindo com febre, mal-estar, dor torácica anterior com irradiação para a esquerda, piorando com a inspiração profunda e melhorando ao sentar-se. O diagnóstico provável é pleurite aguda.\nIII. Paciente com quadro de dor torácica que surge durante os movimentos ventilatórios, em especial na inspiração profunda ou na movimentação dos braços e do pescoço. Trata-se de uma dor bem localizada e desencadeada pela compressão de um ponto. É provável que essa dor seja de origem musculoesquelética.\nEstá correto o que se afirma em:",
        "interactionType": "multiple-choice",
        "options": [
            "A) Apenas I e II estão corretas",
            "B) Apenas I e III estão corretas",
            "C) Apenas II e III estão corretas",
            "D) I, II e III estão corretas",
            "E) Nenhuma das alternativas anteriores"
        ],
        "gabarito": "Alternativa C (Apenas II e III estão corretas).\n\n**COMENTÁRIO DO GABARITO:**\n\n• I — FALSO: Pacientes portadores de estenose aórtica importante ou hipertensão arterial sistêmica de longa data desenvolvem SOBRECARGA CRÔNICA DE PRESSÃO. A resposta adaptativa do ventrículo esquerdo à sobrecarga de pressão é a HIPERTROFIA CONCÊNTRICA (espessamento da parede muscular miocárdica com preservação ou até redução do raio da cavidade ventricular). Nesses casos, o ictus cordis é vigoroso e sustentado (propulsivo), porém MANTÉM-SE EM SUA LOCALIZAÇÃO ANATÔMICA HABITUAL (4º ou 5º EIC esquerdo na linha hemiclavicular). O ictus difuso e desviado para baixo e para a linha axilar decorre de dilatação ventricular por SOBRECARGA DE VOLUME (remodelamento excêntrico da insuficiência aórtica ou insuficiência mitral).\n• II — VERDADEIRO: Na insuficiência aórtica grave crônica, a sobrecarga de volume ejetada e regurgitada ciclicamente induz grande dilatação da câmara ventricular esquerda (hipertrofia excêntrica), deslocando o ictus cordis para o 6º ou 7º espaço intercostal na linha axilar anterior, tornando-o amplo e hipercinético.\n• III — VERDADEIRO: A Quarta Bulha (B4) surge na contração atrial vigorosa contra uma parede ventricular esquerda rígida, hipertrofiada e pouco complacente, sendo achado semiológico clássico da cardiopatia hipertensiva com hipertrofia concêntrica do VE.\n• Resumo Semiológico: Apenas II e III estão corretas (Alternativa C)."
    },
    {
        "type": "MÚLTIPLA ESCOLHA",
        "text": "Homem de 74 anos refere dispneia aos esforços, episódios de tontura ao levantar-se e um episódio de síncope durante caminhada. Ao exame: PA = 118x92 mmHg; pulso radial de pequena amplitude e ascensão lenta; ictus cordis sustentado, não desviado; à ausculta, sopro sistólico rude em crescendo-decrescendo, mais audível no 2º espaço intercostal direito, com irradiação para as carótidas, acompanhado de quarta bulha. O diagnóstico mais provável e o padrão de pulso correspondente são:",
        "interactionType": "multiple-choice",
        "options": [
            "A) Insuficiência aórtica; pulso célere de Corrigan.",
            "B) Estenose aórtica; pulso parvus et tardus.",
            "C) Insuficiência mitral; pulso filiforme.",
            "D) Estenose mitral; pulso alternante.",
            "E) Estenose tricúspide; pulso paradoxal."
        ],
        "gabarito": "Alternativa B.\n\n**COMENTÁRIO DO GABARITO:**\n\n• Análise da Tríade Sintomática Clássica: Homem idoso de 74 anos apresentando a clássica Tríade de Gallavardin da Estenose Aórtica grave do idoso:\n  1. Angina / dor torácica aos esforços;\n  2. Dispneia progressiva aos esforços (insuficiência cardíaca);\n  3. Síncope / tontura aos esforços (baixo débito cerebral por orifício valvar fixo com incapacidade de elevar o débito cardíaco durante exercício).\n• Achados Auscultatórios Patognomônicos:\n  - Sopro sistólico ejetivo áspero em diamante (crescendo-decrescendo), audível com intensidade máxima no Foco Aórtico (2º EIC direito junto ao bordo esternal), que irradia tipicamente para as carótidas bilateralmente e para a fúrcula esternal;\n  - Hipofonese ou desaparecimento do componente aórtico da segunda bulha (A2 apagado por calcificação dos folhetos valvares);\n  - Presença frequente de B4 por hipertrofia concêntrica do VE.\n• Padrão do Pulso Arterial Periférico:\n  - Pulso PARVUS ET TARDUS (ou anacrótico): pulso de pequena amplitude (parvus) e ascensão lenta e tardia com pico retardado (tardus), decorrente da ejeção ventricular difícil através do orifício aórtico severamente estenosado e calcificado.\n• Diagnóstico inequívoco: Estenose Aórtica e Pulso Parvus et Tardus (Alternativa B)."
    },
    {
        "type": "MÚLTIPLA ESCOLHA",
        "text": "Mulher de 58 anos apresenta dispneia progressiva e palpitações. Ao exame: PA = 166x54 mmHg; pulso amplo, de ascensão e queda rápidas, palpável com facilidade em todos os sítios; ictus cordis desviado para baixo e para fora, propulsivo; à ausculta, sopro diastólico aspirativo de alta frequência, mais audível no 3º espaço intercostal esquerdo junto à borda esternal, acentuado com o paciente sentado e inclinado para frente. O diagnóstico mais provável e o comportamento esperado da pressão de pulso são:",
        "interactionType": "multiple-choice",
        "options": [
            "A) Estenose aórtica; pressão de pulso convergente.",
            "B) Insuficiência aórtica; pressão de pulso divergente.",
            "C) Estenose mitral; pressão de pulso convergente.",
            "D) Insuficiência mitral; pressão de pulso normal.",
            "E) Pericardite constritiva; pressão de pulso divergente."
        ],
        "gabarito": "Alternativa B.\nSopro diastólico em Erb (3º EIC E) acentuado à flexão para frente é insuficiência aórtica. A pressão de pulso é divergente (166 - 54 = 112 mmHg) gerando o pulso célere ou \"martelo d'água\"."
    },
    {
        "type": "MÚLTIPLA ESCOLHA",
        "text": "A anamnese e o exame físico do aparelho cardiovascular são de grande relevância na prática médica. Analise as afirmativas a seguir e julgue se cada uma é verdadeira ou falsa:\nI. Paciente 22 anos, sexo feminino, relata inchaço nos pés eventual. Nega outros sintomas ou doenças prévias. Ao exame físico: bom estado geral, eupneica, anictérica, corada, acianótica, consciente, orientada. Aparelho respiratório: murmúrio vesicular presente em ambos hemitórax, sem ruídos adventícios, com expansibilidade preservada. Ao exame cardiovascular: RCR, sopro sistólico no quinto espaço intercostal esquerdo, junto à borda esternal esquerda, com intensidade 1+/6+. Abdome plano, RHA presentes, sem dor à palpação. A valvopatia mais provável diante desse quadro clínico é estenose tricúspide.\nII. Paciente com 70 anos apresenta há 3 meses dispneia aos moderados esforços. Hipertenso há 10 anos em uso regular de atenolol 50 mg/dia. Ao exame físico geral: bom estado, afebril, hidratado, corado, anictérico, FC = 80 bpm; PA = 170 x 60 mmHg; FR = 18 irpm. Ao exame cardiovascular: BRNF em 2T com sopro diastólico 2+/6+ no terceiro espaço intercostal esquerdo, junto à borda esternal esquerda. A valvopatia mais provável diante desse quadro clínico é estenose aórtica.\nAssinale a alternativa correta:",
        "interactionType": "multiple-choice",
        "options": [
            "A) Apenas a assertiva I é verdadeira.",
            "B) Apenas a assertiva II é verdadeira.",
            "C) As duas assertivas são verdadeiras.",
            "D) As duas assertivas são falsas.",
            "E) Não é possível julgar sem exames complementares."
        ],
        "gabarito": "Alternativa B.\n\n**COMENTÁRIO DO GABARITO:**\n\n• Dados Clínicos e Semiológicos do Caso: Mulher de 58 anos com dispneia progressiva, palpitações e exame físico com:\n  1. PA = 166 x 54 mmHg: Pressão arterial sistólica elevada e diastólica acentuadamente rebaixada. A Pressão de Pulso é PP = 166 - 54 = 112 mmHg (> 60 mmHg), caracterizando pressão de pulso DIVERGENTE (ou alargada);\n  2. Pulso amplo, de ascensão rápida e colapso abrupto: clássico Pulso Célere ou Pulso em \"Martelo d'Água\" (Pulso de Corrigan);\n  3. Sopro diastólico aspirativo de alta frequência, suave, em decrescendo, com epicentro no Foco Aórtico Acessório (Ponto de Erb no 3º EIC esquerdo na borda esternal), que se acentua significativamente quando a paciente senta-se, inclina o tórax para a frente e sustenta a expiração completa.\n• Fisiopatologia Integrada: Todos esses elementos decorrem da INSUFICIÊNCIA AÓRTICA (regurgitação aórtica). Na sístole, o ventrículo esquerdo ejeta um volume sistólico hiperdinâmico massivo na aorta (volume efetivo + volume regurgitado), elevando o pico sistólico da PA e a amplitude do pulso. Na diástole, o sangue reflui maciçamente da aorta para o ventrículo esquerdo pela valva incompetente, provocando queda abrupta da pressão diastólica aórtica e o colapso rápido da onda de pulso periférica.\n• Diagnóstico Correto: Insuficiência aórtica com pressão de pulso divergente (Alternativa B)."
    },
    {
        "type": "MÚLTIPLA ESCOLHA",
        "text": "Sobre a caracterização semiológica dos sopros cardíacos, analise as assertivas a seguir:\nI. Na escala de Levine, o sopro de grau 3/6 é aquele audível com frêmito palpável associado.\nII. Um sopro sistólico de grau 1 a 2/6, sem irradiação, em foco pulmonar, em criança assintomática com exame cardiovascular por outro lado normal, sugere sopro inocente.\nIII. O sopro da insuficiência mitral é holossistólico, \"em barra\", e irradia caracteristicamente para a axila.\nIV. O sopro da estenose mitral é um ruflar diastólico de baixa frequência, mais bem audível com a campânula, no foco mitral, frequentemente precedido de estalido de abertura.\nEstá correto o que se afirma em:",
        "interactionType": "multiple-choice",
        "options": [
            "A) Apenas I e III estão corretas.",
            "B) Apenas I, II e IV estão corretas.",
            "C) Apenas II, III e IV estão corretas.",
            "D) Apenas III e IV estão corretas.",
            "E) Todas as alternativas estão corretas."
        ],
        "gabarito": "Alternativa D (As duas assertivas são falsas).\n\n**COMENTÁRIO DO GABARITO:**\n\n• Assertiva I — FALSA: A presença de um sopro sistólico de ejeção grau 1+/6+ no ápice ou base em um indivíduo jovem assintomático, magro ou em atletas pode representar perfeitamente um SOPRO INOCENTE (ou funcional), decorrente de circulação hiperdinâmica sem nenhuma lesão anatômica valvar, e NÃO \"indica invariavelmente cardiopatia estrutural grave que contraindique atividade física\". Além disso, sopros grau 1+/6+ são extremamente suaves e frequentemente transitórios.\n• Assertiva II — FALSA: A intensidade de um sopro cardíaco NÃO é diretamente proporcional à gravidade hemodinâmica da lesão em todas as valvopatias. Pelo contrário: na estenose aórtica crítica em fase terminal com falência miocárdica e choque cardiogênico (baixo débito cardíaco com fração de ejeção muito reduzida), o gradiente pressórico transvalvar diminui tanto que o sopro pode tornar-se tênue ou quase inaudível (\"estenose aórtica silenciosa\"), sem que isso represente lesão leve. Do mesmo modo, na insuficiência mitral aguda com átrio esquerdo não complacente, a equalização rápida de pressões pode encurtar e atenuar o sopro.\n• Portanto, ambas as afirmativas são categoricamente FALSAS (Alternativa D)."
    },
    {
        "type": "VERDADEIRO OU FALSO",
        "text": "Sobre os tipos especiais de pulso arterial, assinale V ou F e marque a sequência correta:\nI. O pulso alternante caracteriza-se pela alternância regular entre uma pulsação de maior e outra de menor amplitude, sendo indicativo de disfunção ventricular esquerda grave.\nII. O pulso filiforme é fino e de difícil percepção, encontrado em estados de choque e hipovolemia.\nIII. O pulso bisferiens apresenta dois picos sistólicos e pode ser encontrado na dupla lesão aórtica e na cardiomiopatia hipertrófica.\nIV. O pulso célere ou de Corrigan é sinônimo de pulso parvus et tardus.\nV. O déficit de pulso é definido pela diferença entre a frequência cardíaca central e o número de pulsações periféricas palpadas.\nMarque a alternativa que representa a sequência correta:",
        "interactionType": "multiple-choice",
        "options": [
            "A) V – V – V – F – V",
            "B) V – F – V – V – F",
            "C) F – V – V – F – V",
            "D) V – V – F – F – V",
            "E) F – V – F – V – V"
        ],
        "gabarito": "Alternativa C (Apenas II, III e IV estão corretas).\n\n**COMENTÁRIO DO GABARITO:**\n\n• I — FALSO: Na clássica Escala de Graduação de Intensidade de Levine e Harvey (de 1 a 6 cruzes):\n  - Grau 1/6: Muito suave, inaudível nos primeiros segundos, audível apenas com concentração em ambiente silencioso;\n  - Grau 2/6: Suave, mas audível imediatamente ao colocar o estetoscópio;\n  - Grau 3/6: Moderadamente intenso, sem frêmito palpável;\n  - Grau 4/6: Sopro INTENSO, OBRIGATORIAMENTE associado à presença de FRÊMITO TÁTIL precordial palpável;\n  - Grau 5/6: Muito intenso, com frêmito palpável, audível com o estetoscópio apenas levemente apoiado (borda da campânula encostada);\n  - Grau 6/6: Tão intenso que é audível mesmo com o estetoscópio ligeiramente afastado da pele do tórax, com frêmito tátil evidente.\n  Portanto, o frêmito surge a partir do Grau 4/6, e não do Grau 3/6.\n• II — VERDADEIRO: Os sopros sistólicos de regurgitação (insuficiência mitral, insuficiência tricúspide e comunicação interventricular) são tipicamente HOLOSSISTÓLICOS (ou pansistólicos), mantendo intensidade constante desde o início de B1 até ultrapassar o componente B2, refletindo o gradiente pressórico constante mantido durante toda a sístole.\n• III — VERDADEIRO: A Manobra de Rivero-Carvalho (ausculta do precórdio durante a inspiração profunda) acentua os sopros originados nas cavidades direitas (insuficiência tricúspide, estenose tricúspide ou pulmonar), pois a pressão negativa intratorácica aumenta o retorno venoso para o átrio e ventrículo direitos.\n• IV — VERDADEIRO: A manobra de Valsalva e a passagem rápida da posição de cócoras para a posição ortostática (em pé) reduzem o retorno venoso e o volume ventricular, atenuando a imensa maioria dos sopros cardíacos sistólicos, com DUAS EXCEÇÕES NOTÁVEIS que aumentam de intensidade: o sopro da CARDIOMIOPATIA HIPERTRÓFICA OBSTRUTIVA (pela aproximação do folheto mitral ao septo hipertrofiado) e o sopro/estalido do PROLAPSO DA VALVA MITRAL.\n• Resumo Semiológico: Apenas II, III e IV estão corretas (Alternativa C)."
    },
    {
        "type": "MÚLTIPLA ESCOLHA",
        "text": "Mulher de 49 anos, com antecedente de febre reumática na infância, apresenta dispneia progressiva e palpitações há 6 meses. Ao exame: pulso radial irregular, com 78 pulsações por minuto; à ausculta do precórdio, contam-se 104 batimentos por minuto, ritmo irregular, com ruflar diastólico em foco mitral precedido de estalido de abertura. Analise as assertivas:\nI. A diferença entre a frequência auscultada e a palpada configura déficit de pulso, de 26 batimentos por minuto.\nII. O ritmo irregular associado ao déficit de pulso sugere fibrilação atrial.\nIII. O ruflar diastólico com estalido de abertura em foco mitral é compatível com estenose mitral, cuja causa mais comum é a doença reumática.\nIV. Nesta paciente, espera-se encontrar quarta bulha proeminente, decorrente da contração atrial vigorosa contra a valva estenosada.\nEstá correto o que se afirma em:",
        "interactionType": "multiple-choice",
        "options": [
            "A) Apenas I e IV estão corretas.",
            "B) Apenas I, II e III estão corretas.",
            "C) Apenas II e IV estão corretas.",
            "D) Apenas III e IV estão corretas.",
            "E) Todas as alternativas estão corretas."
        ],
        "gabarito": "Alternativa A (Sequência: V – V – V – F – V).\n\n**COMENTÁRIO DO GABARITO:**\n\n• (V) O pulso alternante caracteriza-se pela alternância rítmica regular de uma onda de pulso ampla e forte com uma onda de pulso pequena e fraca, mantendo intervalo de tempo rigorosamente constante entre os batimentos, decorrente de variação mecânica do volume de ejeção sistólico no miocárdio em falência sistólica grave do VE.\n• (V) O pulso paradoxal consiste na diminuição fisiológica exagerada da pressão arterial sistólica superior a 10 mmHg durante a fase inspiratória espontânea do ciclo ventilatório.\n• (V) O pulso bisferiens caracteriza-se por duas ondas ou picos sistólicos perceptíveis a cada batimento cardíaco, típico da dupla lesão aórtica (estenose aórtica combinada com insuficiência aórtica importante) e da cardiomiopatia hipertrófica obstrutiva.\n• (F) A assertiva afirma que o pulso célere é de ascensão lenta e pequena amplitude. É FALSO: o pulso célere (em \"martelo d'água\") apresenta ASCENSÃO RÁPIDA, GRANDE AMPLITUDE e colapso abrupto (típico da insuficiência aórtica). O pulso de pequena amplitude e ascensão lenta é o pulso PARVUS ET TARDUS da estenose aórtica.\n• (V) O pulso dicrótico possui uma onda sistólica seguida por uma segunda onda na diástole decorrente do aumento reflexo da incisura dicrótica, podendo ser palpado em febres graves e sepse com hipotensão e vasodilatação periférica.\n• Resumo Semiológico: Sequência correta: V – V – V – F – V (Alternativa A)."
    },
    {
        "type": "MÚLTIPLA ESCOLHA",
        "text": "Sobre o pulso paradoxal, analise as assertivas a seguir:\nI. Define-se pulso paradoxal como a queda da pressão arterial sistólica superior a 10 mmHg durante a inspiração.\nII. É achado clássico do tamponamento cardíaco e da pericardite constritiva, podendo ocorrer também em crise asmática grave e DPOC exacerbada.\nIII. O fenômeno não é verdadeiramente \"paradoxal\": trata-se da exacerbação de uma queda inspiratória fisiológica da pressão sistólica, que normalmente é inferior a 10 mmHg.\nIV. Sua pesquisa é feita durante a aferição da pressão arterial pelo método auscultatório, observando-se a variação dos sons de Korotkoff com o ciclo respiratório.\nEstá correto o que se afirma em:",
        "interactionType": "multiple-choice",
        "options": [
            "A) Apenas I e II estão corretas.",
            "B) Apenas I, II e III estão corretas.",
            "C) Apenas II e IV estão corretas.",
            "D) Apenas III e IV estão corretas.",
            "E) Todas as alternativas estão corretas."
        ],
        "gabarito": "Alternativa B (Apenas I, II e III estão corretas).\n\n**COMENTÁRIO DO GABARITO:**\n\n• I — VERDADEIRO: Paciente jovem/meia-idade com antecedente de febre reumática na infância apresentando dispneia, palpitações e ausculta com: B1 hiperfonética no ápice cardíaco, estalido de abertura valvar na protodiástole e sopro em ruflar diastólico com reforço pré-sistólico no foco mitral (5º EIC na LHC). Esse conjunto semiológico compõe o clássico Ritmo de Duroziez da ESTENOSE MITRAL reumática crônica.\n• II — VERDADEIRO: O ritmo cardíaco com bulhas em cadência completamente desorganizada, intervalos entre batimentos permanentemente irregulares e ausência de B4 no ciclo cardíaco confirma o diagnóstico clínico de FIBRILAÇÃO ATRIAL (complicação frequente da sobrecarga e dilatação mecânica do átrio esquerdo na estenose mitral).\n• III — VERDADEIRO: O reforço pré-sistólico do sopro de estenose mitral decorre da contração atrial vigorosa no final da diástole. Como a paciente entrou em fibrilação atrial e perdeu a contração atrial coordenada, o reforço pré-sistólico desaparece do ruflar diastólico.\n• IV — FALSO: A assertiva afirma que a frequência de pulso radial será idêntica à frequência auscultada no precórdio. Pelo contrário: na Fibrilação Atrial com resposta ventricular elevada ocorre marcante DÉFICIT DE PULSO (a frequência cardíaca central apical é substancialmente maior do que a frequência palpada na artéria radial), pois várias contrações ventriculares prematuras ocorrem antes do enchimento diastólico adequado, gerando débito insuficiente para produzir onda pressórica palpável na periferia.\n• Resumo Semiológico: Apenas I, II e III estão corretas (Alternativa B)."
    },
    {
        "type": "DISCURSIVA",
        "text": "a. Nomeie os cinco focos de ausculta cardíaca e indique a localização anatômica precisa de cada um.\nb. Explique a diferença entre diafragma e campânula do estetoscópio e indique qual usar para B3, B4 e para o ruflar da estenose mitral.\nc. Descreva duas manobras que acentuam achados auscultatórios e diga qual achado cada uma favorece.\nd. Explique a sistematização da ausculta: o que se deve identificar, em ordem, ao auscultar um precórdio.",
        "interactionType": "textarea",
        "gabarito": "Gabarito Comentado e Completo:\n\n(a) Os Cinco Focos Clássicos de Ausculta Cardíaca e suas Localizações Anatômicas:\n1. Foco Aórtico: Localizado no 2º Espaço Intercostal Direito (EICD), imediatamente junto à borda esternal direita.\n2. Foco Pulmonar: Localizado no 2º Espaço Intercostal Esquerdo (EICE), imediatamente junto à borda esternal esquerda.\n3. Foco Aórtico Acessório (ou Ponto de Erb): Localizado no 3º Espaço Intercostal Esquerdo (EICE), na borda esternal esquerda (ideal para auscultar o sopro regurgitante aspirativo da insuficiência aórtica).\n4. Foco Tricúspide: Localizado no 5º Espaço Intercostal Esquerdo (EICE), junto à borda esternal esquerda inferior (ou base do apêndice xifoide).\n5. Foco Mitral (ou Apical): Localizado no 5º Espaço Intercostal Esquerdo (EICE), na linha hemiclavicular esquerda (LHC), correspondendo à projeção do ictus cordis.\n\n(b) Foco Anatômico versus Foco de Ausculta na Propedêutica:\n• Foco Anatômico: É a projeção topográfica real da valva cardíaca no esqueleto torácico. Anatomicamente, as quatro valvas cardíacas encontram-se agrupadas em uma área estreita de apenas alguns centímetros atrás do terço inferior do osso esterno, o que tornaria impossível discriminar os ruídos de cada uma se auscultássemos diretamente sobre elas.\n• Foco de Ausculta (ou Clínico): É o ponto da superfície torácica para onde os sons e sopros gerados por aquela valva específica são mais bem transmitidos e propagados acusticamente pela coluna de fluxo sanguíneo e pelas estruturas mecânicas vizinhas em direção à parede do tórax. Por exemplo, os sons da valva aórtica propagam-se na direção do fluxo da aorta ascendente até o 2º EIC direito.\n\n(c) Diafragma versus Campânula do Estetoscópio:\n• Diafragma (Membrana Plástica Rígida):\n  - Tipo de Som: Projetado para auscultar sons de ALTA FREQUÊNCIA (sons agudos).\n  - Técnica: Deve ser aplicado com pressão firme contra a pele torácica.\n  - Exemplos: Primeira bulha (B1), Segunda bulha (B2), cliques e estalidos de abertura, a grande maioria dos sopros sistólicos ejetivos (estenose aórtica) e regurgitantes (insuficiência mitral), sopro diastólico aspirativo da insuficiência aórtica e o atrito pericárdico.\n• Campânula (Cúpula Aberta Metálica em Cone):\n  - Tipo de Som: Projetada especificamente para captar sons de BAIXA FREQUÊNCIA (sons graves e profundos).\n  - Técnica: Deve ser posicionada de forma LEVE e SUAVE sobre a pele torácica, apenas oclusiva sem comprimir o tecido (pois a compressão transforma a pele do paciente em uma membrana tensa que filtra e anula os sons graves).\n  - Exemplos: Terceira bulha (B3), Quarta bulha (B4) e o sopro diastólico em ruflar da estenose mitral no ápice com o paciente em decúbito lateral esquerdo (Manobra de Pachon)."
    }
];
